"""
Mobilisation Routes
Tracks pregnant women who need a mobilisation follow-up (missed ANC/PMSMA/USG,
near-EDD, unreferred HRP). Cases are auto-generated by scheduler jobs
(see scheduler.py::job_generate_mobilisation_cases). This module only exposes
the read/list view and the "mark mobilised" action — no call/SMS/AI-call
actions are included by design.
"""
from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy.orm import Session, joinedload
from typing import Optional, List
from datetime import datetime
from pydantic import BaseModel

from database import get_db
from models import MobilisationCase, PregnantWoman, User
from auth import get_current_active_user
from audit_utils import log_audit, get_client_info

router = APIRouter(prefix="/mobilisation", tags=["Mobilisation"])


class MarkMobilisedRequest(BaseModel):
    remarks: Optional[str] = None


def _scope_query_to_user(query, current_user: User):
    """Restrict the case list to what this role is allowed to see."""
    if current_user.role == "sub_centre":
        query = query.filter(MobilisationCase.sub_centre_id == current_user.sub_centre_id)
    elif current_user.role == "block":
        query = query.filter(MobilisationCase.block_id == current_user.block_id)
    elif current_user.role == "district":
        query = query.filter(MobilisationCase.district_id == current_user.district_id)
    # PMSMA/USG/DP roles don't own a mobilisation queue; district/block/sub_centre only.
    else:
        query = query.filter(MobilisationCase.id.is_(None))  # empty result for other roles
    return query


def _serialize_case(case: MobilisationCase) -> dict:
    pw = case.pregnant_woman
    return {
        "id": case.id,
        "pregnant_woman_id": case.pregnant_woman_id,
        "pregnant_woman_name": pw.full_name if pw else None,
        "mobile_number": pw.mobile_number if pw else None,
        "is_high_risk": pw.is_high_risk if pw else None,
        "edd_date": pw.edd_date if pw else None,
        "trigger_type": case.trigger_type,
        "trigger_detail": case.trigger_detail,
        "trigger_reference_id": case.trigger_reference_id,
        "sub_centre_id": case.sub_centre_id,
        "block_id": case.block_id,
        "district_id": case.district_id,
        "status": case.status,
        "escalation_level": case.escalation_level,
        "escalated_at": case.escalated_at,
        "mobilised_by": case.mobilised_by,
        "mobilised_by_name": case.mobilised_by_user.full_name if case.mobilised_by_user else None,
        "mobilised_at": case.mobilised_at,
        "remarks": case.remarks,
        "created_at": case.created_at,
        "updated_at": case.updated_at,
    }


@router.get("/")
async def get_mobilisation_cases(
    status_filter: Optional[str] = None,
    trigger_type: Optional[str] = None,
    escalation_level: Optional[str] = None,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db),
):
    """
    List mobilisation cases scoped to the caller's role.
    Default (no status_filter): open cases only (pending + escalated).
    """
    query = db.query(MobilisationCase).options(
        joinedload(MobilisationCase.pregnant_woman),
        joinedload(MobilisationCase.mobilised_by_user),
    )
    query = _scope_query_to_user(query, current_user)

    if status_filter:
        query = query.filter(MobilisationCase.status == status_filter)
    else:
        query = query.filter(MobilisationCase.status.in_(["pending", "escalated"]))

    if trigger_type:
        query = query.filter(MobilisationCase.trigger_type == trigger_type)

    if escalation_level:
        query = query.filter(MobilisationCase.escalation_level == escalation_level)

    cases = query.order_by(
        MobilisationCase.escalation_level.desc(),
        MobilisationCase.created_at.asc(),
    ).all()

    return [_serialize_case(c) for c in cases]


@router.get("/count")
async def get_mobilisation_count(
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db),
):
    """Quick count for dashboard 'mobilisation needed' KPI cards."""
    query = db.query(MobilisationCase).filter(
        MobilisationCase.status.in_(["pending", "escalated"])
    )
    query = _scope_query_to_user(query, current_user)
    return {"count": query.count()}


@router.get("/{case_id}")
async def get_mobilisation_case(
    case_id: int,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db),
):
    case = db.query(MobilisationCase).options(
        joinedload(MobilisationCase.pregnant_woman),
        joinedload(MobilisationCase.mobilised_by_user),
    ).filter(MobilisationCase.id == case_id).first()

    if not case:
        raise HTTPException(status_code=404, detail="Mobilisation case not found")

    return _serialize_case(case)


@router.post("/{case_id}/mark-mobilised")
async def mark_mobilised(
    case_id: int,
    body: MarkMobilisedRequest,
    request: Request,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db),
):
    """
    Mark a mobilisation case as done. Anyone in scope (ANM/Block/District)
    can close a case they can see — there's no call/SMS/AI-call step here,
    this simply records that the woman was mobilised.
    """
    case = db.query(MobilisationCase).filter(MobilisationCase.id == case_id).first()
    if not case:
        raise HTTPException(status_code=404, detail="Mobilisation case not found")

    if case.status == "mobilised":
        raise HTTPException(status_code=400, detail="Case is already marked as mobilised")
    if case.status == "closed":
        raise HTTPException(status_code=400, detail="Case is already closed")

    old_values = {"status": case.status, "escalation_level": case.escalation_level}

    case.status = "mobilised"
    case.mobilised_by = current_user.id
    case.mobilised_at = datetime.now()
    case.remarks = body.remarks

    db.commit()
    db.refresh(case)

    ip_address, user_agent = get_client_info(request)
    log_audit(
        db=db,
        user_id=current_user.id,
        action="MOBILISATION_MARKED_DONE",
        entity_type="MobilisationCase",
        entity_id=case.id,
        old_values=old_values,
        new_values={"status": case.status, "remarks": case.remarks},
        ip_address=ip_address,
        user_agent=user_agent,
    )

    return _serialize_case(case)
