import React, { useState, useEffect } from 'react';
import { Icon } from '@iconify/react/dist/iconify.js';
import { Link } from 'react-router-dom';
import { adminAPI } from '../services/api';
import { getUserRole } from '../services/auth';

const AdministrativeManagementLayer = () => {
    const [activeTab, setActiveTab] = useState('blocks');
    const [blocks, setBlocks] = useState([]);
    const [wards, setWards] = useState([]);
    const [subCentres, setSubCentres] = useState([]);
    const [usgCentres, setUSGCentres] = useState([]);
    const [districts, setDistricts] = useState([]);
    const [loading, setLoading] = useState(false);
    const [showAddModal, setShowAddModal] = useState(false);
    const [showEditModal, setShowEditModal] = useState(false);
    const [showDeleteModal, setShowDeleteModal] = useState(false);
    const [showViewModal, setShowViewModal] = useState(false);
    const [selectedBlock, setSelectedBlock] = useState(null);
    const [selectedWard, setSelectedWard] = useState(null);
    const [selectedSubCentre, setSelectedSubCentre] = useState(null);
    const [selectedUSGCentre, setSelectedUSGCentre] = useState(null);
    const [selectedBlockIds, setSelectedBlockIds] = useState([]);
    const [selectedWardIds, setSelectedWardIds] = useState([]);
    const [districtSearch, setDistrictSearch] = useState('');
    const [blockSearch, setBlockSearch] = useState('');
    const [showDistrictDropdown, setShowDistrictDropdown] = useState(false);
    const [showBlockDropdown, setShowBlockDropdown] = useState(false);
    const [wardSearch, setWardSearch] = useState('');
    const [showWardDropdown, setShowWardDropdown] = useState(false);
    const [viewMappings, setViewMappings] = useState({ blocks: [], wards: [] });
    const [loadingMappings, setLoadingMappings] = useState(false);
    const [formData, setFormData] = useState({ name: '', code: '', district_id: '', block_id: '', ward_id: '', address: '', contact_number: '', contact_person_name: '', email: '', google_map_url: '', is_empanelled: true, is_private: false, block_ids: [], ward_ids: [] });
    const [currentPage, setCurrentPage] = useState(1);
    const [wardCurrentPage, setWardCurrentPage] = useState(1);
    const [subCentreCurrentPage, setSubCentreCurrentPage] = useState(1);
    const [itemsPerPage] = useState(100);
    const [totalUSGCentres, setTotalUSGCentres] = useState(0);
    const [totalWards, setTotalWards] = useState(0);
    const [totalSubCentres, setTotalSubCentres] = useState(0);
    const userRole = getUserRole();